/*
 * @Author: Milodu
 * @Date:   2017-09-13 16:58:59
 * @Last Modified by:   Milodu
 * @Last Modified time: 2017-09-14 10:33:26
 */
exports.data = [
	['[微笑]', '[撇嘴]', '[色]', '[发呆]', '[得意]', '[流泪]', '[害羞]', '[闭嘴]', '[睡]', '[大哭]', '[尴尬]', '[发怒]', '[调皮]', '[呲牙]', '[惊讶]', '[难过]', '[酷]', '[冷汗]', '[抓狂]', '[吐]', '[删除]'],
	['[偷笑]', '[可爱]', '[白眼]', '[傲慢]', '[饥饿]', '[困]', '[惊恐]', '[流汗]', '[憨笑]', '[大兵]', '[奋斗]', '[咒骂]', '[疑问]', '[嘘]', '[晕]', '[折磨]', '[哀]', '[骷髅]', '[敲打]', '[再见]', '[删除]'],
	['[擦汗]', '[抠鼻]', '[鼓掌]', '[糗大了]', '[坏笑]', '[左哼哼]', '[右哼哼]', '[哈欠]', '[鄙视]', '[委屈]', '[快哭了]', '[阴险]', '[亲亲]', '[吓]', '[可怜]', '[菜刀]', '[西瓜]', '[啤酒]', '[篮球]', '[乒乓]', '[删除]'],
	['[咖啡]', '[饭]', '[猪头]', '[玫瑰]', '[凋谢]', '[示爱]', '[爱心]', '[心碎]', '[蛋糕]', '[闪电]', '[炸弹]', '[刀]', '[足球]', '[瓢虫]', '[便便]', '[月亮]', '[太阳]', '[礼物]', '[拥抱]', '[强]', '[删除]'],
	['[弱]', '[握手]', '[胜利]', '[抱拳]', '[勾引]', '[拳头]', '[差劲]', '[爱你]', '[no]', '[ok]', '[爱情]', '[飞吻]', '[跳跳]', '[发抖]', '[怄火]', '[转圈]', '[磕头]', '[回头]', '[跳绳]', '[挥手]', '[删除]'],
	['[跳高]', '[吼叫]', '[练武]', '[左摆]', '[右摆]', '[囍]', '[鞭炮]', '[灯笼]', '[发]', '[麦克风]', '[手袋]', '[信]', '[帅]', '[庆祝]', '[蜡烛]', '[生气]', '[棒棒糖]', '[奶瓶]', '[面条]', '[香蕉]', '[删除]'],
	['[飞机]', '[汽车]', '[车头]', '[车厢]', '[车尾]', '[多云]', '[下雨]', '[钞票]', '[熊猫]', '[灯泡]', '[风车]', '[闹钟]', '[雨伞]', '[气球]', '[钻戒]', '[沙发]', '[厕纸]', '[药丸]', '[手枪]', '[青蛙]', '[删除]']
];
exports.imgList = [{
	"key": "[微笑]",
	"value": "/static/img/qqface/1.gif"
}, {
	"key": "[撇嘴]",
	"value": "/static/img/qqface/2.gif"
}, {
	"key": "[色]",
	"value": "/static/img/qqface/3.gif"
}, {
	"key": "[发呆]",
	"value": "/static/img/qqface/4.gif"
}, {
	"key": "[得意]",
	"value": "/static/img/qqface/5.gif"
}, {
	"key": "[流泪]",
	"value": "/static/img/qqface/6.gif"
}, {
	"key": "[害羞]",
	"value": "/static/img/qqface/7.gif"
}, {
	"key": "[闭嘴]",
	"value": "/static/img/qqface/8.gif"
}, {
	"key": "[睡]",
	"value": "/static/img/qqface/9.gif"
}, {
	"key": "[大哭]",
	"value": "/static/img/qqface/10.gif"
}, {
	"key": "[尴尬]",
	"value": "/static/img/qqface/11.gif"
}, {
	"key": "[发怒]",
	"value": "/static/img/qqface/12.gif"
}, {
	"key": "[调皮]",
	"value": "/static/img/qqface/13.gif"
}, {
	"key": "[呲牙]",
	"value": "/static/img/qqface/14.gif"
}, {
	"key": "[惊讶]",
	"value": "/static/img/qqface/15.gif"
}, {
	"key": "[难过]",
	"value": "/static/img/qqface/16.gif"
}, {
	"key": "[酷]",
	"value": "/static/img/qqface/17.gif"
}, {
	"key": "[冷汗]",
	"value": "/static/img/qqface/18.gif"
}, {
	"key": "[抓狂]",
	"value": "/static/img/qqface/19.gif"
}, {
	"key": "[吐]",
	"value": "/static/img/qqface/20.gif"
}, {
	"key": "[偷笑]",
	"value": "/static/img/qqface/21.gif"
}, {
	"key": "[可爱]",
	"value": "/static/img/qqface/22.gif"
}, {
	"key": "[白眼]",
	"value": "/static/img/qqface/23.gif"
}, {
	"key": "[傲慢]",
	"value": "/static/img/qqface/24.gif"
}, {
	"key": "[饥饿]",
	"value": "/static/img/qqface/25.gif"
}, {
	"key": "[困]",
	"value": "/static/img/qqface/26.gif"
}, {
	"key": "[惊恐]",
	"value": "/static/img/qqface/27.gif"
}, {
	"key": "[流汗]",
	"value": "/static/img/qqface/28.gif"
}, {
	"key": "[憨笑]",
	"value": "/static/img/qqface/29.gif"
}, {
	"key": "[大兵]",
	"value": "/static/img/qqface/30.gif"
}, {
	"key": "[奋斗]",
	"value": "/static/img/qqface/31.gif"
}, {
	"key": "[咒骂]",
	"value": "/static/img/qqface/32.gif"
}, {
	"key": "[疑问]",
	"value": "/static/img/qqface/33.gif"
}, {
	"key": "[嘘]",
	"value": "/static/img/qqface/34.gif"
}, {
	"key": "[晕]",
	"value": "/static/img/qqface/35.gif"
}, {
	"key": "[折磨]",
	"value": "/static/img/qqface/36.gif"
}, {
	"key": "[哀]",
	"value": "/static/img/qqface/37.gif"
}, {
	"key": "[骷髅]",
	"value": "/static/img/qqface/38.gif"
}, {
	"key": "[敲打]",
	"value": "/static/img/qqface/39.gif"
}, {
	"key": "[再见]",
	"value": "/static/img/qqface/40.gif"
}, {
	"key": "[擦汗]",
	"value": "/static/img/qqface/41.gif"
}, {
	"key": "[抠鼻]",
	"value": "/static/img/qqface/42.gif"
}, {
	"key": "[鼓掌]",
	"value": "/static/img/qqface/43.gif"
}, {
	"key": "[糗大了]",
	"value": "/static/img/qqface/44.gif"
}, {
	"key": "[坏笑]",
	"value": "/static/img/qqface/45.gif"
}, {
	"key": "[左哼哼]",
	"value": "/static/img/qqface/46.gif"
}, {
	"key": "[右哼哼]",
	"value": "/static/img/qqface/47.gif"
}, {
	"key": "[哈欠]",
	"value": "/static/img/qqface/48.gif"
}, {
	"key": "[鄙视]",
	"value": "/static/img/qqface/49.gif"
}, {
	"key": "[委屈]",
	"value": "/static/img/qqface/50.gif"
}, {
	"key": "[快哭了]",
	"value": "/static/img/qqface/51.gif"
}, {
	"key": "[阴险]",
	"value": "/static/img/qqface/52.gif"
}, {
	"key": "[亲亲]",
	"value": "/static/img/qqface/53.gif"
}, {
	"key": "[吓]",
	"value": "/static/img/qqface/54.gif"
}, {
	"key": "[可怜]",
	"value": "/static/img/qqface/55.gif"
}, {
	"key": "[菜刀]",
	"value": "/static/img/qqface/56.gif"
}, {
	"key": "[西瓜]",
	"value": "/static/img/qqface/57.gif"
}, {
	"key": "[啤酒]",
	"value": "/static/img/qqface/58.gif"
}, {
	"key": "[篮球]",
	"value": "/static/img/qqface/59.gif"
}, {
	"key": "[乒乓]",
	"value": "/static/img/qqface/60.gif"
}, {
	"key": "[咖啡]",
	"value": "/static/img/qqface/61.gif"
}, {
	"key": "[饭]",
	"value": "/static/img/qqface/62.gif"
}, {
	"key": "[猪头]",
	"value": "/static/img/qqface/63.gif"
}, {
	"key": "[玫瑰]",
	"value": "/static/img/qqface/64.gif"
}, {
	"key": "[凋谢]",
	"value": "/static/img/qqface/65.gif"
}, {
	"key": "[示爱]",
	"value": "/static/img/qqface/66.gif"
}, {
	"key": "[爱心]",
	"value": "/static/img/qqface/67.gif"
}, {
	"key": "[心碎]",
	"value": "/static/img/qqface/68.gif"
}, {
	"key": "[蛋糕]",
	"value": "/static/img/qqface/69.gif"
}, {
	"key": "[闪电]",
	"value": "/static/img/qqface/70.gif"
}, {
	"key": "[炸弹]",
	"value": "/static/img/qqface/71.gif"
}, {
	"key": "[刀]",
	"value": "/static/img/qqface/72.gif"
}, {
	"key": "[足球]",
	"value": "/static/img/qqface/73.gif"
}, {
	"key": "[瓢虫]",
	"value": "/static/img/qqface/74.gif"
}, {
	"key": "[便便]",
	"value": "/static/img/qqface/75.gif"
}, {
	"key": "[月亮]",
	"value": "/static/img/qqface/76.gif"
}, {
	"key": "[太阳]",
	"value": "/static/img/qqface/77.gif"
}, {
	"key": "[礼物]",
	"value": "/static/img/qqface/78.gif"
}, {
	"key": "[拥抱]",
	"value": "/static/img/qqface/79.gif"
}, {
	"key": "[强]",
	"value": "/static/img/qqface/80.gif"
}, {
	"key": "[弱]",
	"value": "/static/img/qqface/81.gif"
}, {
	"key": "[握手]",
	"value": "/static/img/qqface/82.gif"
}, {
	"key": "[胜利]",
	"value": "/static/img/qqface/83.gif"
}, {
	"key": "[抱拳]",
	"value": "/static/img/qqface/84.gif"
}, {
	"key": "[勾引]",
	"value": "/static/img/qqface/85.gif"
}, {
	"key": "[拳头]",
	"value": "/static/img/qqface/86.gif"
}, {
	"key": "[差劲]",
	"value": "/static/img/qqface/87.gif"
}, {
	"key": "[爱你]",
	"value": "/static/img/qqface/88.gif"
}, {
	"key": "[no]",
	"value": "/static/img/qqface/89.gif"
}, {
	"key": "[ok]",
	"value": "/static/img/qqface/90.gif"
}, {
	"key": "[爱情]",
	"value": "/static/img/qqface/91.gif"
}, {
	"key": "[飞吻]",
	"value": "/static/img/qqface/92.gif"
}, {
	"key": "[跳跳]",
	"value": "/static/img/qqface/93.gif"
}, {
	"key": "[发抖]",
	"value": "/static/img/qqface/94.gif"
}, {
	"key": "[怄火]",
	"value": "/static/img/qqface/95.gif"
}, {
	"key": "[转圈]",
	"value": "/static/img/qqface/96.gif"
}, {
	"key": "[磕头]",
	"value": "/static/img/qqface/97.gif"
}, {
	"key": "[回头]",
	"value": "/static/img/qqface/98.gif"
}, {
	"key": "[跳绳]",
	"value": "/static/img/qqface/99.gif"
}, {
	"key": "[挥手]",
	"value": "/static/img/qqface/100.gif"
}, {
	"key": "[跳高]",
	"value": "/static/img/qqface/101.gif"
}, {
	"key": "[吼叫]",
	"value": "/static/img/qqface/102.gif"
}, {
	"key": "[练武]",
	"value": "/static/img/qqface/103.gif"
}, {
	"key": "[左摆]",
	"value": "/static/img/qqface/104.gif"
}, {
	"key": "[右摆]",
	"value": "/static/img/qqface/105.gif"
}, {
	"key": "[囍]",
	"value": "/static/img/qqface/106.gif"
}, {
	"key": "[鞭炮]",
	"value": "/static/img/qqface/107.gif"
}, {
	"key": "[灯笼]",
	"value": "/static/img/qqface/108.gif"
}, {
	"key": "[发]",
	"value": "/static/img/qqface/109.gif"
}, {
	"key": "[麦克风]",
	"value": "/static/img/qqface/110.gif"
}, {
	"key": "[手袋]",
	"value": "/static/img/qqface/111.gif"
}, {
	"key": "[信]",
	"value": "/static/img/qqface/112.gif"
}, {
	"key": "[帅]",
	"value": "/static/img/qqface/113.gif"
}, {
	"key": "[庆祝]",
	"value": "/static/img/qqface/114.gif"
}, {
	"key": "[蜡烛]",
	"value": "/static/img/qqface/115.gif"
}, {
	"key": "[生气]",
	"value": "/static/img/qqface/116.gif"
}, {
	"key": "[棒棒糖]",
	"value": "/static/img/qqface/117.gif"
}, {
	"key": "[奶瓶]",
	"value": "/static/img/qqface/118.gif"
}, {
	"key": "[面条]",
	"value": "/static/img/qqface/119.gif"
}, {
	"key": "[香蕉]",
	"value": "/static/img/qqface/120.gif"
}, {
	"key": "[飞机]",
	"value": "/static/img/qqface/121.gif"
}, {
	"key": "[汽车]",
	"value": "/static/img/qqface/122.gif"
}, {
	"key": "[车头]",
	"value": "/static/img/qqface/123.gif"
}, {
	"key": "[车厢]",
	"value": "/static/img/qqface/124.gif"
}, {
	"key": "[车尾]",
	"value": "/static/img/qqface/125.gif"
}, {
	"key": "[多云]",
	"value": "/static/img/qqface/126.gif"
}, {
	"key": "[下雨]",
	"value": "/static/img/qqface/127.gif"
}, {
	"key": "[钞票]",
	"value": "/static/img/qqface/128.gif"
}, {
	"key": "[熊猫]",
	"value": "/static/img/qqface/129.gif"
}, {
	"key": "[灯泡]",
	"value": "/static/img/qqface/130.gif"
}, {
	"key": "[风车]",
	"value": "/static/img/qqface/131.gif"
}, {
	"key": "[闹钟]",
	"value": "/static/img/qqface/132.gif"
}, {
	"key": "[雨伞]",
	"value": "/static/img/qqface/133.gif"
}, {
	"key": "[气球]",
	"value": "/static/img/qqface/134.gif"
}, {
	"key": "[钻戒]",
	"value": "/static/img/qqface/135.gif"
}, {
	"key": "[沙发]",
	"value": "/static/img/qqface/136.gif"
}, {
	"key": "[厕纸]",
	"value": "/static/img/qqface/137.gif"
}, {
	"key": "[药丸]",
	"value": "/static/img/qqface/138.gif"
}, {
	"key": "[手枪]",
	"value": "/static/img/qqface/139.gif"
}, {
	"key": "[青蛙]",
	"value": "/static/img/qqface/140.gif"
}]